### ISSUE TITLE
Early Compatibility Test!

### ISSUE THREAD

**Issue by jarroddavis68** [tinyBigGAMES/GamePascal#1]
@limelect, and anyone else that is interested in testing this? I want to know if it will compile pascal source code to an executable and that executable runs on your configuration. I want to find out the minimum specifications I can get this project to run on. 

- Delphi/FreePascal (Win64)
- Windows 64bit

If so, just reply here and I will be in touch. Thanks in advance.

**Comment by limelect** [comment]
And the source?

**Comment by jarroddavis68** [comment]
You can find it here:
https://tinybiggames.com/temp/gp_tests.zip

**Comment by jarroddavis68** [comment]
it should have compiled a test01.exe, that then should also be able to run on your same machine. If it works, then this is the first step. This will be a game library, but also a compiler as a service. The next step is as I flesh out the library, just make sure it continues to work and not break for your config.

So, you was able to compile without issues?

**Comment by limelect** [comment]
It compiles on 10.2.3

**Comment by limelect** [comment]
![image](https://user-images.githubusercontent.com/4199131/211516948-0eddd37a-a31a-4cfe-ba89-013311eadbe1.png)

**Comment by jarroddavis68** [comment]
NICE! Sweet. It should also work with FreePascal. I will have to add the appropriate $MODE switch in GamePascal unit, but I will get to that soon. Now I just keep moving in this direction while not breaking compatibility.

Oh, you are running on Win7 correct?

**Comment by limelect** [comment]
However, I don't like DLL because I do not know what's inside.
Specially whiteout sources.
I am a proffesional

**Comment by limelect** [comment]
Yes win 7

**Comment by limelect** [comment]
I do not like to upgrade when things work without a problem.
See how many problems when one upgrade Delphi.
I started with D1!! then 2 5 6 7 then 10

**Comment by jarroddavis68** [comment]
win7, ok.

yea, for now because
1) I am currently using some commercial lib/components to make this all work, so sources can't be released.
2) The dll isolates all compatibilities issuess (as what you described when moving from one Delphi version to the next, which is a royal pain) and will continue to work across many Delphi versions and OS version.

**Comment by limelect** [comment]
Which commercial components?

**Comment by jarroddavis68** [comment]
email me and I can discuss that with you.

**Comment by limelect** [comment]
limelect at gmail dot com

**Comment by limelect** [comment]
also limelect.com

**Comment by jarroddavis68** [comment]
Ok

**Comment by jarroddavis68** [comment]
look for my mail @tinybiggames.com, if google nukes it, sigh.

**Comment by soastao** [comment]
I agree with limelect's opinion， I also don't like DLL because I do not know what's inside.

I like DelphiGamekit，If there is a bug, I can also see the source code to find the reason，this point is very important.

**Comment by soastao** [comment]
Even if the function is less, the source code is more valuable than DLL，I would rather not want the function of commercial components

**Comment by jarroddavis68** [comment]
But you use Delphi itself, it's made of many components (DLLs) that you do not know what's inside? If you fire up Visual Studio and compile some code, many things that you have zero knowledge of about, yet you may make use of it?

DelphiGameKit, at the lower level it sits on top of SDL + other C based libs, which must be in the form of a DLL, which is dynamically linked to at runtime. I just made the process as non-intrusive and painless as possible, but nevertheless, at the core of it, there is that "DLL".

**Comment by soastao** [comment]
Okay, you are right
